### ISSUE TITLE
provision on Azure fails due to credssp on AD DC

### ISSUE THREAD

**Issue by ffirg** [mgmt-sa-tiger-team/skylight#10]
< PLAY [Configure Active Directory Domain Controller] >
 -----------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

 ________________________
< TASK [Gathering Facts] >
 ------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [windc]: FAILED! => {"msg": "The installed version of WinRM does not support transport(s) [u'credssp']"}
 ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

localhost                  : ok=40   changed=18   unreachable=0    failed=0
windc                      : ok=0    changed=0    unreachable=0    failed=1

**Comment by cigamit** [comment]
Did you install credssp on your host your running the playbooks from?

**Comment by ffirg** [comment]
Yes already installed, but just tried a 'sudo pip install pywinrm[credssp] --force —upgrade’ 
re-testing now...

**Comment by ffirg** [comment]
Got further but now getting a python crash

/ TASK [manage-azure-instances : Generate instructor \
\ inventory]                                         /
 ----------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

changed: [localhost]
 _________________________________________________
/ TASK [manage-azure-instances : Generate student \
\ inventories]                                    /
 -------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

changed: [localhost] => (item=1)
 _____________________________________________________
< PLAY [Configure Active Directory Domain Controller] >
 -----------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

 ________________________
< TASK [Gathering Facts] >
 ------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

objc[10839]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[10839]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.

**Comment by cigamit** [comment]
What ansible version and what OS are you provisioning from?  

Also take a quick look at this 
https://github.com/ansible/ansible/issues/31869

**Comment by ffirg** [comment]
macOS Mojave 10.14.3
Python 2.7.15
ansible 2.7.10

I’ll take a look at that issue and try the workaround. Thanks!

**Comment by cigamit** [comment]
Another thing to note, if you are provisioning in Azure, you can also do it from the Azure Cloud Shell instead of your local laptop.
https://github.com/mgmt-sa-tiger-team/skylight/blob/master/docs/AZURE_CLOUD_SHELL.md

**Comment by cigamit** [comment]
Closing, as this isn't really an issue with Skylight, but with ansible on OSx, but please feel free to reopen if you still can't work through the issue.

**Comment by ffirg** [comment]
I can confirm that this fixed this issue on my Mac:
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
