### ISSUE TITLE
Azure provisioning should use managed disks

### ISSUE THREAD

**Issue by nitzmahone** [mgmt-sa-tiger-team/skylight#11]
If you change the Azure provisioning stuff to use managed disks, you can ditch the storage account, and should speed up the provisioning process a bit.

**Comment by cigamit** [comment]
From the last time I looked at it, managed disks were a bit pricer.  I will go back and do a cost analysis of what we are provisioning for a standard workshop size and what it costs after ~3 days of run time.   Price may be close enough now that it doesn't matter.

**Comment by cigamit** [comment]
This is now resolved
