### ISSUE TITLE
Use wait_for_connection in provisioning

### ISSUE THREAD

**Issue by nitzmahone** [mgmt-sa-tiger-team/skylight#12]
If you move the `add_hosts` below the `wait_for` stuff, you should be able to use `wait_for_connection` with `delegate_to` instead of `wait_for` to actually ensure that the hosts are manageable by Ansible, not just that the ports are open (more an issue with the WinRM stuff than SSH, but still)...

**Comment by oatakan** [comment]
Thanks @nitzmahone , good suggestion. I used this approach in other playbooks. Will test and validate.

**Comment by cigamit** [comment]
Its 2am here in Kazakhstan (after a 20 hour flight) so it just be the lack of sleep addling my brain, but if you moved the add_host below the wait_for_connection; How would the host with associated username/password be available for the delegate_to to work?

**Comment by cigamit** [comment]
Added this commit for Azure / VMWare provisioners
46586b86c7fcada8dda28fd411fd77615d748ebb
will need to rework the EC2 provisioner a bit before it can be used there
(since we have to wait a bit before the password is available from AWS)

**Comment by cigamit** [comment]
This is now resolved
