### ISSUE TITLE
Don't use cygwin

### ISSUE THREAD

**Issue by nitzmahone** [mgmt-sa-tiger-team/skylight#16]
Now that WSL is supported in Server 2019, maybe update to that and install WSL from https://github.com/mgmt-sa-tiger-team/skylight/blob/master/roles/windows-workstation/tasks/ansible.yml instead of demoing Ansible in an environment we explicitly don't support (and that is flaky for Ansible usage)- we definitely don't want to encourage users to do that when WSL works much better and is lowercase-s supported. ;)

**Comment by oatakan** [comment]
@cigamit I'm not sure where the cygwin requirement came from. Sounds like WSL should be the way to go on this if we really need the linux subsystem. Once we identify the impact, we can test out with WSL potentially.

**Comment by cigamit** [comment]
If you check, that playbook isn't actually loaded, it was just there from when I was testing getting Ansible to work on 2012 and 2016.

**Comment by cigamit** [comment]
Ill remove this playbook, as its not used at all
