### ISSUE TITLE
Provisioner fails for gitlab host - missing sshpass program?

### ISSUE THREAD

**Issue by ffirg** [mgmt-sa-tiger-team/skylight#18]
/ TASK [windows-common : Add Ansible group to a local Remote \
\ Management Users]                                          /
 ------------------------------------------------------------
changed: [s1-w1]
 ______________________________
< PLAY [Configure GitLab Host] >
 ------------------------------
 ________________________
< TASK [Gathering Facts] >
 ------------------------

fatal: [gitlab]: FAILED! => {"msg": "to use the 'ssh' connection type with passwords, you must install the sshpass program"}

gitlab                     : ok=0    changed=0    unreachable=0    failed=1
localhost                  : ok=40   changed=28   unreachable=0    failed=0
s1-w1                      : ok=7    changed=6    unreachable=0    failed=0
windc                      : ok=18   changed=14   unreachable=0    failed=0

**Comment by cigamit** [comment]
If you are provisioning from your mac, you will need to install sshpass on it.
A quick google shows
`brew install http://git.io/sshpass.rb
`

**Comment by ffirg** [comment]
Yep, just trying that now. Seems to have got past the last error. Thanks! Perhaps the provisioner needs this added in as a pre-req or just update the docs?

**Comment by ffirg** [comment]
All worked after this :) Great work, thanks guys.
