### ISSUE TITLE
Exercise1.adoc - credentials and formatting

### ISSUE THREAD

**Issue by bowlofpie** [mgmt-sa-tiger-team/skylight#20]
* In Exercise1.adoc in the "*Logging into Tower*" section, it says "*Your Tower instance has already been pre-configured for LDAP Login, so use your student credentials without the domain name to login.*" This is not the case and you need to leave off the domain name.

* Also, in "*Inventories*" - "*Step 2*" - there is some formatting text that needs fixing: “image::images/inventory="Edit Inventory",width=1000]"

**Comment by cigamit** [comment]
1. "use your student credentials **without** the domain name"
   so it is telling you to leave off the domain.
2. Thanks for catching that, will create a fix shortly.

**Comment by ffirg** [comment]
credentials in the docs (Exercise 1, Step 3) still mention to use the domain name, although the screen shot shows it without. Can this be updated as it's a little confusing.
