### ISSUE TITLE
Exercise5.adoc - figures, sync, test

### ISSUE THREAD

**Issue by bowlofpie** [mgmt-sa-tiger-team/skylight#24]
* The “*Figure 2. Empty site.yml*” still refers to the previous figure for "*iis_basic*" and should refer to "iis_advanced"

* In "*Section 5*" - there is a missing step to do a project scm sync.

* In "*Section 6*" - after running the job the user should be told to check the new website on port 8080

**Comment by cigamit** [comment]
Thanks, Fixes added
