### ISSUE TITLE
Exercise7.adoc - formatting, instruction

### ISSUE THREAD

**Issue by bowlofpie** [mgmt-sa-tiger-team/skylight#26]
* "*Section 4*", "*step 3"* “*MULTIPLE CHOICE OPTIONS*” and “*DEFAULT ANSWER*” are bulleted with new-lines. These should just be a single-spaced list for easier copy&paste by the student.

* "*Section 4*", "*step 3*" “*Now add another field.*” - There needs to be some instruction for the student here on how to do this.

* "*Section 4*", "*step 3*" “*Now add another field.*” “*MULTIPLE CHOICE OPTIONS*” are bulleted with new-lines. These should just be a single-spaced list for easier copy&paste by the student.

**Comment by cigamit** [comment]
1. Fixed
2. Fixed
3. Fixed
Also updated the images to be for Ex 7 and not others

**Comment by cigamit** [comment]
Closed via 2bd124636c6e3bc82c1a860c6aa49a4a1e73e30c
