### ISSUE TITLE
Requirements - python packages, tower license, AWS AMIs, credentials

### ISSUE THREAD

**Issue by bowlofpie** [mgmt-sa-tiger-team/skylight#27]
* python packages - I needed the following: pywinrm, boto, boto3, requests.

* Tower license - this is also needed and put into `../skylight/tower_license.json` or in variable "*tower_license*". Perhaps obtained from `https://store.ansible.com/redhat/tower_license/`

* AWS AWIs for RHEL and Windows - these hard-coded AMI IDs failed for me so I found current ones in AWS. Perhaps these vary on region? Perhaps this can be determined programmatically during playbook run? 

* When running the playbook, I got this error: *"module_stdout": "Please login as the user \"ec2-user\" rather than the user \"root\".\r\n\r\n"* so for a quick&dirty I changed the `root_user` variable in my `vars/custom.yml` to:
` # Root user (ec2-user for AWS)`
` root_user: ec2-user`
Perhaps for AWS AMIs this should be changed away from *root* ?

**Comment by cigamit** [comment]
Are you suggesting we create a requirements
1. Yes, those are basic Ansible requirements for working with AWS and Windows and are mostly listed in the Readme already.  There are different requirements if using Azure.
2. Yes, it will alert you if you don't have this.  I will add a note to the readme also to make it clearer.
3. We have now added code (a few days ago) to auto select the AMIs based on the region
4. Yes, the comment on the variable already states to use ec2-user for AWS

I will update the readme with a little better wording around the requirements.  Most of it is already there.

**Comment by cigamit** [comment]
Closed via wrong commit
