### ISSUE TITLE
Provisioner fails to create DNS A record on windc host on ec2

### ISSUE THREAD

**Issue by ffirg** [mgmt-sa-tiger-team/skylight#31]
task path: /Users/pgriffit/skylight/roles/windows-ad-controller/tasks/main.yml:95
ok: [windc] => {"attempts": 1, "changed": false, "msg": "DNS Zone: Present: 1.0.10.in-addr.arpa"}
 _______________________________________________________
/ TASK [windows-ad-controller : Create DNS A record for \
\ gitlab]                                               /
 -------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

task path: /Users/pgriffit/skylight/roles/windows-ad-controller/tasks/main.yml:104
fatal: [windc]: FAILED! => {"changed": false, "msg": "Failed to get gitlab record in ansibleworkshop.com zone on WINDC server."}
 ____________

**Comment by ffirg** [comment]
Just pulled latest master branch and will re-try

**Comment by EmergentWorkshop** [comment]
Please take me off this list, I never subscribed

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ffirg** [comment]
This is still a problem with the latest master branch...
task path: /Users/pgriffit/skylight/roles/windows-ad-controller/tasks/main.yml:62
ok: [windc] => {"attempts": 1, "changed": false, "msg": "DNS Zone: Present: 1.0.10.in-addr.arpa"}
 _______________________________________________________
/ TASK [windows-ad-controller : Create DNS A record for \
\ gitlab]                                               /
 -------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

task path: /Users/pgriffit/skylight/roles/windows-ad-controller/tasks/main.yml:71
fatal: [windc]: FAILED! => {"changed": false, "msg": "Failed to get gitlab record in ansibleworkshop.com zone on WINDC server."}

**Comment by ffirg** [comment]
This issue is related to having ansible 2.8rc2 installed. Downgraded back to 2.7 and it's now working.
