### ISSUE TITLE
What about adding in a Linux server as well?

### ISSUE THREAD

**Issue by ffirg** [mgmt-sa-tiger-team/skylight#32]
It would be great to see Linux being managed alongside the Windows node as well.

**Comment by cigamit** [comment]
This workshop is mostly for teaching windows admins, most of whom don't know anything about Linux.  Trying to teach them how Linux works may be throwing a bit too much at them at once.

**Comment by cigamit** [comment]
We will circle back to this later once we start adding more lessons into the Advanced Lessons.
