### ISSUE TITLE
admin portal should be able to delete a user record

### ISSUE THREAD

**Issue by mrjoshuap** [mgmt-sa-tiger-team/skylight#35]
I've had a couple points where I'd like to be able to delete a user from the database; thus freeing up a student lab environment.  Preferably this is an admin function in list.php to clear student seats where a single person submitted multiple logins with different email addresses.

**Comment by cigamit** [comment]
Good idea and easy enough to accomplish.  The only issue may be if they actually started work on one and then continued it on another, the git repo wouldn't be cleaned out.  Problem for another day.

**Comment by mrjoshuap** [comment]
Mine was for the single use case of someone accidentally taking two and not using one; I had thought about the alternative, and was thinking of working on a "reset student lab" idea and if it was worth it.  So far, when I've encountered it, I have them grab another open lab environment...

**Comment by cigamit** [comment]
Added a commit to add this, and changed the Grading function to only grade when you click the button to request it.  This speeds the normal page loads instead of regrading on every page load.  Last grade is stored in the DB until you tell it to regrade again.
