### ISSUE TITLE
Microsoft SQL Server error

### ISSUE THREAD

**Issue by medberry** [mgmt-sa-tiger-team/skylight#37]
Seeing deploy errors in ec2 (that weren't there during the recent class held in Austin). I'm wondering if the "find ami" function for Tower is picking up the wrong ami.

> TASK [manage-ec2-instances : Wait for tower instance creation to complete] ****************************************************
> failed: [localhost] (item={'_ansible_parsed': True, '_ansible_item_result': True, '_ansible_item_label': u'1', u'ansible_job_id': u'329075883890.24614', 'failed': False, u'started': 1, 'changed': True, 'item': u'1', u'finished': 0, u'results_file': u'/home/medberry/.ansible_async/329075883890.24614', '_ansible_ignore_errors': None, '_ansible_no_log': False}) => {"ansible_job_id": "329075883890.24614", "attempts": 1, "changed": false, "finished": 1, "item": {"ansible_job_id": "329075883890.24614", "changed": true, "failed": false, "finished": 0, "item": "1", "results_file": "/home/medberry/.ansible_async/329075883890.24614", "started": 1}, "msg": "Instance creation failed => UnsupportedOperation: Microsoft SQL Server Enterprise Edition is not supported for the instance type 't2.medium'."}
> failed: [localhost] (item={'_ansible_parsed': True, '_ansible_item_result': True, '_ansible_item_label': u'2', u'ansible_job_id': u'336951201221.24642', 'failed': False, u'started': 1, 'changed': True, 'item': u'2', u'finished': 0, u'results_file': u'/home/medberry/.ansible_async/336951201221.24642', '_ansible_ignore_errors': None, '_ansible_no_log': False}) => {"ansible_job_id": "336951201221.24642", "attempts": 1, "changed": false, "finished": 1, "item": {"ansible_job_id": "336951201221.24642", "changed": true, "failed": false, "finished": 0, "item": "2", "results_file": "/home/medberry/.ansible_async/336951201221.24642", "started": 1}, "msg": "Instance creation failed => UnsupportedOperation: Microsoft SQL Server Enterprise Edition is not supported for the instance type 't2.medium'."}
> failed: [localhost] (item={'_ansible_parsed': True, '_ansible_item_result': True, '_ansible_item_label': u'3', u'ansible_job_id': u'339176757268.24668', 'failed': False, u'started': 1, 'changed': True, 'item': u'3', u'finished': 0, u'results_file': u'/home/medberry/.ansible_async/339176757268.24668', '_ansible_ignore_errors': None, '_ansible_no_log': False}) => {"ansible_job_id": "339176757268.24668", "attempts": 1, "changed": false, "finished": 1, "item": {"ansible_job_id": "339176757268.24668", "changed": true, "failed": false, "finished": 0, "item": "3", "results_file": "/home/medberry/.ansible_async/339176757268.24668", "started": 1}, "msg": "Instance creation failed => UnsupportedOperation: Microsoft SQL Server Enterprise Edition is not supported for the instance type 't2.medium'."}
> 
> PLAY RECAP ********************************************************************************************************************
> localhost

**Comment by cigamit** [comment]
Hmm certainly possible, I will play with it tonight and see what is happening

**Comment by cigamit** [comment]
Yes, it seems to be selecting 
_RHEL-7.6_HVM_GA-20181017-x86_64-0-Hourly2-GP2-SQL_2017_Enterprise-2019.04.09_
I will add an owner to force it to use a AMI that is supplied by Red Hat, instead of this particular one supplied by Amazon.

**Comment by cigamit** [comment]
Resolved by a5e98567986f3c2ba6d6b4044e267e01c97331a8
