### ISSUE TITLE
Provisioning fails at the step waiting for DC instance. 

### ISSUE THREAD

**Issue by etgredhat-ansible-demo** [mgmt-sa-tiger-team/skylight#5]
There seems to be an issue with ami-050202fb72f001b47

TASK [manage-ec2-instances : Wait for docs instance creation to complete] ******
changed: [localhost] => (item={'_ansible_parsed': True, '_ansible_item_result': True, '_ansible_item_label': u'1', u'ansible_job_id': u'301580481176.576', 'failed': False, u'started': 1, 'changed': True, 'item': u'1', u'finished': 0, u'results_file': u'/var/lib/awx/.ansible_async/301580481176.576', '_ansible_ignore_errors': None, '_ansible_no_log': False})

TASK [manage-ec2-instances : Wait for DC instance creation to complete] ********
failed: [localhost] (item={'_ansible_parsed': True, '_ansible_item_result': True, '_ansible_item_label': u'1', u'ansible_job_id': u'240466855789.441', 'failed': False, u'started': 1, 'changed': True, 'item': u'1', u'finished': 0, u'results_file': u'/var/lib/awx/.ansible_async/240466855789.441', '_ansible_ignore_errors': None, '_ansible_no_log': False}) => {"ansible_job_id": "240466855789.441", "attempts": 1, "changed": false, "finished": 1, "item": {"ansible_job_id": "240466855789.441", "changed": true, "failed": false, "finished": 0, "item": "1", "results_file": "/var/lib/awx/.ansible_async/240466855789.441", "started": 1}, "msg": "Instance creation failed => AuthFailure: Not authorized for images: [ami-050202fb72f001b47]"}

Not sure if anyone else is experiencing this issue, 

But changing the ami to below in vars/main.yml seems to have passed the step - but then fails at the step of windows host joining the domain.   

--
ec2_windows_ami: ami-017f677e #   Windows 2016 Base
--
 
are there any other ami's in the us-northeast region that has been used and verified?

**Comment by cigamit** [comment]
Seems Amazon removed the image we were using
I just swapped to this one without issue
ami-0bf148826ef491d16

Most Windows AMIs seem to be hit or miss it seems.  I know I tried at least 15 before that just didn't work.

**Comment by cigamit** [comment]
This should be fixed by using the new AMI.
