### ISSUE TITLE
Documentation mentions a desktop link that points to Tower that is missing

### ISSUE THREAD

**Issue by rmahroua** [mgmt-sa-tiger-team/skylight#55]
In `Exercise1.html`, there is mention of a link in the 'Logging into Tower' section that points to the Ansible Tower instance. 
However, there is no such link - see below for a screen of my `student1` workstation:

<img width="693" alt="Screen Shot 2019-07-12 at 10 20 54 AM" src="https://user-images.githubusercontent.com/29074292/61146386-c04b9180-a48e-11e9-8ce5-26d8e86b3a4f.png">

**Comment by cigamit** [comment]
Did you login as student1? It will only be on the specific students account that the server belongs to.

**Comment by rmahroua** [comment]
Ah my bad. You are correct, I was logged in as the administrator user. I should have paid more attention

**Comment by cigamit** [comment]
NP, that's why I add the icons under specific users, just so I immediately know if someone is logged into the wrong account.
