### ISSUE TITLE
credssp: 'module' object has no attribute 'i2d_RSAPublicKey' when using the `win_ping` module

### ISSUE THREAD

**Issue by rmahroua** [mgmt-sa-tiger-team/skylight#57]
Hey,
I tried to run the `win_ping` module against my Windows host, but the Job in Ansible Tower fails with the following message:

<img width="1055" alt="Screen Shot 2019-07-15 at 10 22 30 AM" src="https://user-images.githubusercontent.com/29074292/61235942-9d69e900-a6eb-11e9-8581-8e55fb8db710.png">

It seems to be related to the `PyOpenSSL` package or the `requests-credssp` Pip module, per [1] and [2]
```
[root@s1tower ec2-user]# pip show PyOpenSSL
---
Metadata-Version: 2.1
Name: pyOpenSSL
Version: 19.0.0

root@s1tower ec2-user]# pip show requests-credssp
---
Metadata-Version: 2.1
Name: requests-credssp
Version: 1.0.2
```

---
[1] https://stackoverflow.com/questions/54601736/ansible-winrm-credssp-module-object-has-no-attribute-tlsv1-2-method
[2] https://github.com/ansible/ansible/issues/23843

**Comment by rmahroua** [comment]
When using `ansible_winrm_transport: basic` as the host variable, the job executes.

**Comment by cigamit** [comment]
What AMI is it using for Tower?  I am running another test now, but I didn't have any issues with credssp last week.

It seems that every new version of requests-credssp and PyOpenSSL keep breaking things, I might pin them to a specific version if they broke things again.

**Comment by cigamit** [comment]
Also, what Windows AMI, just to make sure my test is accurate.

**Comment by rmahroua** [comment]
So:

* Tower: `RHEL-7.6_HVM_GA-20190128-x86_64-0-Hourly2-GP2 (ami-04642fc8fca1e8e67)`
* Windows host: `Windows_Server-2019-English-Core-Base-2019.06.12 (ami-067db9db9a69322de)`

**Comment by cigamit** [comment]
Ok, I get the same issue against Windows 2016 also.  I will see if I can work around it via pinning specific versions, or else we will just swap it to NTLM.

**Comment by cigamit** [comment]
I've downgraded just about every relevant python module, but still couldn't get it working, so i think we will swap to ntlm for the time being.

**Comment by oatakan** [comment]
I couldn't replicate this issue. It works for me against the master branch.

rhel 7 for tower: ami-0240b09539b9692a0
win 2019: ami-04f46af0096c1d8b9

**Comment by rmahroua** [comment]
Thanks. I could do more testing with other AMIs or packages version.

**Comment by ffirg** [comment]
I'm getting this error too. Tried twice now with x2 provisioners run in AWS.

**Comment by ffirg** [comment]
I'm also finding that basic auth doesn't work, although ntlm does.

**Comment by ffirg** [comment]
It seems that a 'yum remove pyOpenSSL' might fix most of the credssp issue, at least from the CLI running as the awx user. I also ran a sudo pip uninstall requests-credssp and install beforehand.

**Comment by ffirg** [comment]
The requests-credssp package in the default tower venv seems to be way out-of-date.
If you update requests-credssp to 1.0.2 in there then credssp works.

**Comment by rmahroua** [comment]
@ffirg does Tower interacts with Ansible CLI  - or does it manage its own set of modules? I can try to remove the PyOpenSSL package. Is there a way to limit on that package? I noticed that yum removed a set of related package that I could not reinstall afterwards via Yum.

**Comment by ffirg** [comment]
@rmahroua tower has its own set of modules under a virtualenv. See https://docs.ansible.com/ansible-tower/latest/html/upgrade-migration-guide/virtualenv.html for details. 

I updated that venv using:

# source /var/lib/awx/venv/ansible/bin/activate
# umask 0022
# pip install --upgrade requests-credssp
# deactivate

Really you should create a new venv, update that and then configure tower to be able to use it but this only being a test env and my laziness meant I wanted a quick fix :)

**Comment by rmahroua** [comment]
Looks like the latest version of Tower (3.5.2-1) solves the issue :) 
https://docs.ansible.com/ansible-tower/latest/html/installandreference/release_notes.html
I tested with the latest version and that fixed my issue.
