### ISSUE TITLE
In exercise3.adoc, we need to confirm the student email address before being able to connect to Gitlab

### ISSUE THREAD

**Issue by rmahroua** [mgmt-sa-tiger-team/skylight#58]
In the third activity, it says:

> This may take as long as 30 seconds to push. If you’re interested in validating the code is in git, you can connect to gitlab to verify. Open Chrome and connect to https://gitlab.ansibleworkshop.com. Login with your AD user (student#) and password and you should see your repo.

You are ready to automate!

However, when attempting to log in for the first time, Gitlab requires the email to be confirmed:
<img width="1116" alt="Screen Shot 2019-07-15 at 1 58 46 PM" src="https://user-images.githubusercontent.com/29074292/61248795-ae752300-a708-11e9-972e-284e1e00cad2.png">

Is there a way to bypass that since email client is not configured on the workstation?
Thanks

**Comment by cigamit** [comment]
This here was suppose to take care of that.
https://github.com/mgmt-sa-tiger-team/skylight/blob/master/roles/gitlab-postconfig/tasks/api.yml#L39

It wasn't an issue when we were using an old version of gitlab, but the new version seems to have changed a good bit.

**Comment by cigamit** [comment]
I was just able to test it, and am able to login without issue.  Also, use LDAP login, not Standard.

**Comment by rmahroua** [comment]
Thanks for the feedback. I'm wondering if Gitlab somewhat resets this after logging in from the "standard login". Because after doing that, even trying through LDAP would not work. In the PR that I opened, I expanded in one of the exercise to make sure students don't click the wrong tab.

**Comment by cigamit** [comment]
Closing this, as there is now a PR for it.
