### ISSUE TITLE
Validate the tower license after it is applied (or prior)

### ISSUE THREAD

**Issue by medberry** [mgmt-sa-tiger-team/skylight#61]
2102  curl -s -k -u admin:MyPassw0rd21 https://$TOWERADDRESS/api/v2/config/ |python -m  json.tool

config will get the license info (as known by tower) including "license_info:free_instances" (available) and seconds until license expires "license_info:time_remaining"

Examining the tower_license.json may also be  beneficial. Just report and end if license is out of date. Could be an early pre-check.

license_date (make sure greater than time.time)

**Comment by cigamit** [comment]
Fixed via commit
