### ISSUE TITLE
"Permission denied"

### ISSUE THREAD

**Issue by ShaddGallegos** [mgmt-sa-tiger-team/skylight#64]
I am unable to get skylight to work  

I keep getting a "Permission denied"
**"item": "/etc/sysconfig/network-scripts/ifcfg-eth0",
    "msg": "The destination directory (/etc/sysconfig/network-scripts) is not writable by the current user. Error was: [Errno 13] Permission denied: '/etc/sysconfig/network-scripts/.ansible_tmpjCNGfOifcfg-eth0'"**

I am using root_user: ec2-user in my extra vars is this the wrong place 

Skylight

Using Directions at https://github.com/mgmt-sa-tiger-team/skylight

Failing Component

#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

TASK [linux-common : Remove PeerDNS=yes entry] *********************************
task path: /var/lib/awx/projects/_11__windows/roles/linux-common/tasks/main.yml:12

<18.207.144.65> ESTABLISH SSH CONNECTION FOR USER: ec2-user
<18.207.144.65> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/var/lib/awx/projects/_11__windows/workshops/spg-skylight-test/sgallegos-spg-skylight-test-private.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ec2-user"' -o ConnectTimeout=10 -o ControlPath=/tmp/awx_240_w6b3gzq1/cp/17de2f4bcf 18.207.144.65 '/bin/sh -c '"'"'echo ~ec2-user && sleep 0'"'"''
<18.207.144.65> (0, '/home/ec2-user\\n', '')
<18.207.144.65> ESTABLISH SSH CONNECTION FOR USER: ec2-user
<18.207.144.65> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/var/lib/awx/projects/_11__windows/workshops/spg-skylight-test/sgallegos-spg-skylight-test-private.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ec2-user"' -o ConnectTimeout=10 -o ControlPath=/tmp/awx_240_w6b3gzq1/cp/17de2f4bcf 18.207.144.65 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/ec2-user/.ansible/tmp/ansible-tmp-1564779515.14-38520014040043 `" && echo ansible-tmp-1564779515.14-38520014040043="` echo /home/ec2-user/.ansible/tmp/ansible-tmp-1564779515.14-38520014040043 `" ) && sleep 0'"'"''
<18.207.144.65> (0, 'ansible-tmp-1564779515.14-38520014040043=/home/ec2-user/.ansible/tmp/ansible-tmp-1564779515.14-38520014040043\\n', '')
Using module file /usr/lib/python2.7/site-packages/ansible/modules/files/lineinfile.py
<18.207.144.65> PUT /var/lib/awx/.ansible/tmp/ansible-local-70qMzd_/tmpPYQysA TO /home/ec2-user/.ansible/tmp/ansible-tmp-1564779515.14-38520014040043/AnsiballZ_lineinfile.py
<18.207.144.65> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/var/lib/awx/projects/_11__windows/workshops/spg-skylight-test/sgallegos-spg-skylight-test-private.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ec2-user"' -o ConnectTimeout=10 -o ControlPath=/tmp/awx_240_w6b3gzq1/cp/17de2f4bcf '[18.207.144.65]'
<18.207.144.65> (0, 'sftp> put /var/lib/awx/.ansible/tmp/ansible-local-70qMzd_/tmpPYQysA /home/ec2-user/.ansible/tmp/ansible-tmp-1564779515.14-38520014040043/AnsiballZ_lineinfile.py\\n', '')
<18.207.144.65> ESTABLISH SSH CONNECTION FOR USER: ec2-user
<18.207.144.65> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/var/lib/awx/projects/_11__windows/workshops/spg-skylight-test/sgallegos-spg-skylight-test-private.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ec2-user"' -o ConnectTimeout=10 -o ControlPath=/tmp/awx_240_w6b3gzq1/cp/17de2f4bcf 18.207.144.65 '/bin/sh -c '"'"'chmod u+x /home/ec2-user/.ansible/tmp/ansible-tmp-1564779515.14-38520014040043/ /home/ec2-user/.ansible/tmp/ansible-tmp-1564779515.14-38520014040043/AnsiballZ_lineinfile.py && sleep 0'"'"''
<18.207.144.65> (0, '', '')
<18.207.144.65> ESTABLISH SSH CONNECTION FOR USER: ec2-user
<18.207.144.65> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/var/lib/awx/projects/_11__windows/workshops/spg-skylight-test/sgallegos-spg-skylight-test-private.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ec2-user"' -o ConnectTimeout=10 -o ControlPath=/tmp/awx_240_w6b3gzq1/cp/17de2f4bcf -tt 18.207.144.65 '/bin/sh -c '"'"'/usr/bin/python /home/ec2-user/.ansible/tmp/ansible-tmp-1564779515.14-38520014040043/AnsiballZ_lineinfile.py && sleep 0'"'"''
<18.207.144.65> (1, '\\r\\n{"msg": "The destination directory (/etc/sysconfig/network-scripts) is not writable by the current user. Error was: [Errno 13] Permission denied: \\'/etc/sysconfig/network-scripts/.ansible_tmpjCNGfOifcfg-eth0\\'", "failed": true, "exception": "Traceback (most recent call last):\\\\n  File \\\\"/tmp/ansible_lineinfile_payload_B4Eh12/ansible_lineinfile_payload.zip/ansible/module_utils/basic.py\\\\", line 2243, in atomic_move\\\\n    dir=b_dest_dir, suffix=b_suffix)\\\\n  File \\\\"/usr/lib64/python2.7/tempfile.py\\\\", line 304, in mkstemp\\\\n    return _mkstemp_inner(dir, prefix, suffix, flags)\\\\n  File \\\\"/usr/lib64/python2.7/tempfile.py\\\\", line 239, in _mkstemp_inner\\\\n    fd = _os.open(file, flags, 0600)\\\\nOSError: [Errno 13] Permission denied: \\'/etc/sysconfig/network-scripts/.ansible_tmpjCNGfOifcfg-eth0\\'\\\\n", "invocation": {"module_args": {"directory_mode": null, "force": null, "remote_src": null, "backrefs": false, "insertafter": null, "path": "/etc/sysconfig/network-scripts/ifcfg-eth0", "owner": null, "follow": false, "validate": null, "group": null, "insertbefore": null, "unsafe_writes": null, "create": false, "state": "present", "content": null, "serole": null, "setype": null, "selevel": null, "regexp": "^PEERDNS=yes", "line": "", "src": null, "seuser": null, "delimiter": null, "mode": null, "firstmatch": false, "attributes": null, "backup": false}}}\\r\\n', 'Shared connection to 18.207.144.65 closed.\\r\\n')
<18.207.144.65> Failed to connect to the host via ssh: Shared connection to 18.207.144.65 closed.
<18.207.144.65> ESTABLISH SSH CONNECTION FOR USER: ec2-user
<18.207.144.65> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/var/lib/awx/projects/_11__windows/workshops/spg-skylight-test/sgallegos-spg-skylight-test-private.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ec2-user"' -o ConnectTimeout=10 -o ControlPath=/tmp/awx_240_w6b3gzq1/cp/17de2f4bcf 18.207.144.65 '/bin/sh -c '"'"'rm -f -r /home/ec2-user/.ansible/tmp/ansible-tmp-1564779515.14-38520014040043/ > /dev/null 2>&1 && sleep 0'"'"''
<18.207.144.65> (0, '', '')
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_lineinfile_payload_B4Eh12/ansible_lineinfile_payload.zip/ansible/module_utils/basic.py", line 2243, in atomic_move
    dir=b_dest_dir, suffix=b_suffix)
  File "/usr/lib64/python2.7/tempfile.py", line 304, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib64/python2.7/tempfile.py", line 239, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 13] Permission denied: '/etc/sysconfig/network-scripts/.ansible_tmpjCNGfOifcfg-eth0'

failed: [gitlab] (item=/etc/sysconfig/network-scripts/ifcfg-eth0) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "attributes": null,
            "backrefs": false,
            "backup": false,
            "content": null,
            "create": false,
            "delimiter": null,
            "directory_mode": null,
            "firstmatch": false,
            "follow": false,
            "force": null,
            "group": null,
            "insertafter": null,
            "insertbefore": null,
            "line": "",
            "mode": null,
            "owner": null,
            "path": "/etc/sysconfig/network-scripts/ifcfg-eth0",
            "regexp": "^PEERDNS=yes",
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "state": "present",
            "unsafe_writes": null,
            "validate": null
        }
    },
    "item": "/etc/sysconfig/network-scripts/ifcfg-eth0",
    "msg": "The destination directory (/etc/sysconfig/network-scripts) is not writable by the current user. Error was: [Errno 13] Permission denied: '/etc/sysconfig/network-scripts/.ansible_tmpjCNGfOifcfg-eth0'"
}

PLAY RECAP *********************************************************************
gitlab                     : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0  
localhost                  : ok=64   changed=36   unreachable=0    failed=0    skipped=8    rescued=0    ignored=0  
s1-win1                    : ok=7    changed=6    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  
windc                      : ok=17   changed=14   unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

**Comment by cigamit** [comment]
I don't run this from Tower, so Orcun would be more help.  Make sure you don't have a credential set for the playbook.  We use the variable and the key generated to connect, and then tell the playbook to become root.  I believe the credential can try to override parts of that that conflict.

**Comment by oatakan** [comment]
This sounds like a sudo issue, try checking ' Enable Privilige Escalation' on the job template, or disable if already enabled. Also check the machine credential and see if any privilige escalation user is specified there. You can just use any user name there.

**Comment by cigamit** [comment]
Shadd, do you still have this issue, or can we close it?

**Comment by ShaddGallegos** [comment]
it is good it wasnt an issue with the installer it is an issue with 
documentation

Your Friend

Shadd Gallegos
Senior Solutions Architect
shadd@redhat.com
919-602-0001
