### ISSUE TITLE
Failed to connect to Gitlab server

### ISSUE THREAD

**Issue by etgredhat-ansible-demo** [mgmt-sa-tiger-team/skylight#67]
Hi all,

Consistently running into a failure in the Gitlab Post Config steps after the 120 second pause:

...
TASK [gitlab-postconfig : GitLab Post | Remove set root password script] *******
changed: [gitlab]

TASK [gitlab-postconfig : sleep 2 minute to allow root to initialize after password set] ***
Pausing for 120 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [gitlab]

TASK [gitlab-postconfig : GitLab Post | Create local users] ********************
failed: [gitlab] (item=1) => {"changed": false, "item": "1", "msg": "Failed to connect to Gitlab server: 'message' "}

PLAY RECAP *********************************************************************
gitlab                     : ok=29   changed=19   unreachable=0    failed=1   
localhost                  : ok=66   changed=36   unreachable=0    failed=0   
s1-win1                    : ok=7    changed=6    unreachable=0    failed=0   
windc                      : ok=17   changed=14   unreachable=0    failed=0   

Any ideas?

**Comment by etgredhat-ansible-demo** [comment]
More error info below:

TASK [gitlab-postconfig : GitLab Post | Create local users] ********************
task path: /Users/bstineha/Downloads/Ansible/Repos/Skylight/skylight-master/roles/gitlab-postconfig/tasks/main.yml:56
<54.79.102.57> ESTABLISH SSH CONNECTION FOR USER: ec2-user
<54.79.102.57> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/Users/bstineha/Downloads/Ansible/Repos/Skylight/skylight-master/workshops/skylightB/Brian-skylightB-private.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ec2-user -o ConnectTimeout=10 -o ControlPath=/Users/bstineha/.ansible/cp/146e4d5f60 54.79.102.57 '/bin/sh -c '"'"'echo ~ec2-user && sleep 0'"'"''
<54.79.102.57> (0, '/home/ec2-user\n', '')
<54.79.102.57> ESTABLISH SSH CONNECTION FOR USER: ec2-user
<54.79.102.57> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/Users/bstineha/Downloads/Ansible/Repos/Skylight/skylight-master/workshops/skylightB/Brian-skylightB-private.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ec2-user -o ConnectTimeout=10 -o ControlPath=/Users/bstineha/.ansible/cp/146e4d5f60 54.79.102.57 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/ec2-user/.ansible/tmp/ansible-tmp-1567059282.15-144777344580633 `" && echo ansible-tmp-1567059282.15-144777344580633="` echo /home/ec2-user/.ansible/tmp/ansible-tmp-1567059282.15-144777344580633 `" ) && sleep 0'"'"''
<54.79.102.57> (0, 'ansible-tmp-1567059282.15-144777344580633=/home/ec2-user/.ansible/tmp/ansible-tmp-1567059282.15-144777344580633\n', '')
Using module file /Library/Python/2.7/site-packages/ansible/modules/source_control/gitlab_user.py
<54.79.102.57> PUT /Users/bstineha/.ansible/tmp/ansible-local-28766BKm0Ec/tmpXrDh9f TO /home/ec2-user/.ansible/tmp/ansible-tmp-1567059282.15-144777344580633/AnsiballZ_gitlab_user.py
<54.79.102.57> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/Users/bstineha/Downloads/Ansible/Repos/Skylight/skylight-master/workshops/skylightB/Brian-skylightB-private.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ec2-user -o ConnectTimeout=10 -o ControlPath=/Users/bstineha/.ansible/cp/146e4d5f60 '[54.79.102.57]'
<54.79.102.57> (0, 'sftp> put /Users/bstineha/.ansible/tmp/ansible-local-28766BKm0Ec/tmpXrDh9f /home/ec2-user/.ansible/tmp/ansible-tmp-1567059282.15-144777344580633/AnsiballZ_gitlab_user.py\n', '')
<54.79.102.57> ESTABLISH SSH CONNECTION FOR USER: ec2-user
<54.79.102.57> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/Users/bstineha/Downloads/Ansible/Repos/Skylight/skylight-master/workshops/skylightB/Brian-skylightB-private.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ec2-user -o ConnectTimeout=10 -o ControlPath=/Users/bstineha/.ansible/cp/146e4d5f60 54.79.102.57 '/bin/sh -c '"'"'chmod u+x /home/ec2-user/.ansible/tmp/ansible-tmp-1567059282.15-144777344580633/ /home/ec2-user/.ansible/tmp/ansible-tmp-1567059282.15-144777344580633/AnsiballZ_gitlab_user.py && sleep 0'"'"''
<54.79.102.57> (0, '', '')
<54.79.102.57> ESTABLISH SSH CONNECTION FOR USER: ec2-user
<54.79.102.57> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/Users/bstineha/Downloads/Ansible/Repos/Skylight/skylight-master/workshops/skylightB/Brian-skylightB-private.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ec2-user -o ConnectTimeout=10 -o ControlPath=/Users/bstineha/.ansible/cp/146e4d5f60 -tt 54.79.102.57 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-tyxleievnbiidvekufrjcqvtcqqolqgt; /usr/bin/python /home/ec2-user/.ansible/tmp/ansible-tmp-1567059282.15-144777344580633/AnsiballZ_gitlab_user.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<54.79.102.57> (1, '/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html\r\n  InsecureRequestWarning)\r\n\r\n{"msg": "Failed to connect to Gitlab server: \'message\' ", "failed": true, "exception": "WARNING: The below traceback may *not* be related to the actual failure.\\n  File \\"/tmp/ansible_gitlab_user_payload_eO4CYa/__main__.py\\", line 321, in main\\n    git.login(user=login_user, password=login_password)\\n  File \\"/usr/lib/python2.7/site-packages/gitlab/__init__.py\\", line 74, in login\\n    msg = request.json()[\'message\']\\n", "invocation": {"module_args": {"username": "student1", "group": null, "name": "student1", "confirm": false, "sshkey_name": null, "login_user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "login_token": null, "sshkey_file": null, "server_url": "https://gitlab.ansibleworkshop.com", "access_level": null, "state": "present", "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "validate_certs": false, "email": "student1@ansibleworkshop.com"}}}\r\n', 'Shared connection to 54.79.102.57 closed.\r\n')
<54.79.102.57> ESTABLISH SSH CONNECTION FOR USER: ec2-user
<54.79.102.57> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/Users/bstineha/Downloads/Ansible/Repos/Skylight/skylight-master/workshops/skylightB/Brian-skylightB-private.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ec2-user -o ConnectTimeout=10 -o ControlPath=/Users/bstineha/.ansible/cp/146e4d5f60 54.79.102.57 '/bin/sh -c '"'"'rm -f -r /home/ec2-user/.ansible/tmp/ansible-tmp-1567059282.15-144777344580633/ > /dev/null 2>&1 && sleep 0'"'"''
<54.79.102.57> (0, '', '')
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_gitlab_user_payload_eO4CYa/__main__.py", line 321, in main
    git.login(user=login_user, password=login_password)
  File "/usr/lib/python2.7/site-packages/gitlab/__init__.py", line 74, in login
    msg = request.json()['message']

failed: [gitlab] (item=1) => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "access_level": null, 
            "confirm": false, 
            "email": "student1@ansibleworkshop.com", 
            "group": null, 
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "login_token": null, 
            "login_user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "name": "student1", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "server_url": "https://gitlab.ansibleworkshop.com", 
            "sshkey_file": null, 
            "sshkey_name": null, 
            "state": "present", 
            "username": "student1", 
            "validate_certs": false
        }
    }, 
    "item": "1", 
    "msg": "Failed to connect to Gitlab server: 'message' "
}

PLAY RECAP *********************************************************************
gitlab                     : ok=25   changed=7    unreachable=0    failed=1   
localhost                  : ok=65   changed=19   unreachable=0    failed=0   
s1-win1                    : ok=6    changed=0    unreachable=0    failed=0   
windc                      : ok=15   changed=0    unreachable=0    failed=0

**Comment by etgredhat-ansible-demo** [comment]
Any feedback on this? I'm now getting a connection refused error:

TASK [gitlab-postconfig : GitLab Post | Create local users] ********************
failed: [gitlab] (item=1) => {"changed": false, "item": "1", "msg": "Failed to connect to Gitlab server: ('Connection aborted.', error(111, 'Connection refused')) "}

For what it's worth, an older version of the repo I pulled down closer to mid-July deploys successfully.

**Comment by oatakan** [comment]
You can try setting gitlab version or upgrade ansible to 2.8.x. See below:

# install latest version of gitlab when using ansible 2.8
# enable gitlab_version below when using ansible < 2.8
# gitlab_version: "10.0.6-ce.0.el7"

**Comment by etgredhat-ansible-demo** [comment]
Cheers, Orcun! 

Just needed to update to 2.8
