### ISSUE TITLE
Ansible 2.8 broke the synchronize module for Python 2

### ISSUE THREAD

**Issue by cigamit** [mgmt-sa-tiger-team/skylight#68]
When using Python2 and Ansible 2.8, I get this error when provisioning to VMWare

TASK [docs_setup : Copy lab guides to server] *****************************************************************************************************************************************************************
fatal: [docs]: FAILED! => {"changed": false, "cmd": "sshpass -d12 /usr/bin/rsync --delay-updates -F --compress --archive '--rsh=/usr/bin/ssh -S none -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' '--rsync-path=sudo rsync' '--out-format=<<CHANGED>>%i %n%L' /home/cigamit/projects/skylight/docs/lab_guide/ ''", "msg": "[Errno 32] Broken pipe", "rc": 32}

Seems that Ansible 2.8 broke things
https://github.com/ansible/ansible/issues/56629

**Comment by oatakan** [comment]
As an alternative we can consider using git module to clone from the project repo rather than copy with synchronize. as a side benefit this should also improve the performance during the provisioning.

We would probably use git clone to a temp directory first then use copy with remote_src=yes to recursively copy to target directory.

**Comment by cigamit** [comment]
Now that I think about it, I think a simpler fix would have been just to revert to the copy module if the synchronize module failed.  By making it do a get checkout, I can't test changes to the docs before they are committed to the repo.

**Comment by oatakan** [comment]
> Now that I think about it, I think a simpler fix would have been just to revert to the copy module if the synchronize module failed. By making it do a get checkout, I can't test changes to the docs before they are committed to the repo.

agreed. we can change this implementation to use the copy to keep things simple.

**Comment by cigamit** [comment]
This is resolved
