### ISSUE TITLE
azure deploy error on dns entry for gitlab

### ISSUE THREAD

**Issue by chadhellyea** [mgmt-sa-tiger-team/skylight#7]
TASK [windows-ad-controller : Create DNS A record for gitlab] ************************************************************************************************************
fatal: [skylight-dc]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: \"hostvars['gitlab']\" is undefined\n\nThe error appearsto have been in '/home/chad/skylight/roles/windows-ad-controller/tasks/main.yml': line 96, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create DNS A record for gitlab\n  ^ here\n"}
        to retry, use: --limit @/home/chad/skylight/provision.retry

**Comment by cigamit** [comment]
I believe I already fixed that last night via e6a3b820c51bec1b5872436ca6da24a6e3045f5a

**Comment by cigamit** [comment]
Let me know if that didn't resolve it for you, I also added a lot of other fixes tonight that you may want to pull in.
