### ISSUE TITLE
Issues in the win_ec2_user_data.j2 template?

### ISSUE THREAD

**Issue by rmahroua** [mgmt-sa-tiger-team/skylight#74]
Hey,
lately, a couple of folks in my team were not able to provision the environment. The provisioning fails when the "cloud-init" script tries to configure WinRM on the machines.

Upon further troubleshooting, I located a couple of issues in the [`win_ec2_user_data.j2` template](https://github.com/mgmt-sa-tiger-team/skylight/blob/771ac417ef1730e8cbd05f5927fb9d29d3b4a067/roles/manage-ec2-instances/templates/win_ec2_user_data.j2#L7)

1. The two `net stop` and `net start` command that restart the updates services are on the same line. This leads PowerShell to throw an error:
<img width="1190" alt="Screen Shot 2019-09-17 at 4 57 16 PM" src="https://user-images.githubusercontent.com/29074292/65087888-39260880-d96c-11e9-8875-29dfd4c6f8a6.png">

After updating the file as follows, I no longer have any error:
```
reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update" /v AUOptions /t REG_DWORD /d 1 /f
# New line for the two net commands
net stop wuauserv
net start wuauserv
```

2. The PowerShell script that configures WinRM fails with the following error:
<img width="1643" alt="Screen Shot 2019-09-17 at 4 58 21 PM" src="https://user-images.githubusercontent.com/29074292/65087925-5fe43f00-d96c-11e9-818f-64a4ee7491a1.png">

This leads the script to never complete. The WinRM listener is up on the HTTPs port, however, the firewall rule never gets added. This error is not systematic, but still happens about 10% of the time.
I added two lines to modify two keys in the registry as follows:
```
# Enable WinRM
# RM: Potential fix for WinRM configuration
reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\WinRM\Service" /t REG_DWORD /v AllowBasic /d 1 /f
reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\WinRM\Client" /t REG_DWORD /v AllowBasic /d 1 /f

Invoke-WebRequest -Uri https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1 -OutFile C:\ConfigureRemotingForAnsible.ps1
C:\ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP
```

Here's the final template:
```
<powershell>
# Disable .Net Optimization Service
Get-ScheduledTask *ngen* | Disable-ScheduledTask

# Disable Windows Auto Updates
# https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/troubleshooting-windows-instances.html#high-cpu-issue
reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update" /v AUOptions /t REG_DWORD /d 1 /f
net stop wuauserv
net start wuauserv

# Disable Windows Defender Monitoring
Set-MpPreference -DisableRealtimeMonitoring $true

# Enable WinRM
# RM: Potential fix for WinRM configuration
reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\WinRM\Service" /t REG_DWORD /v AllowBasic /d 1 /f
reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\WinRM\Client" /t REG_DWORD /v AllowBasic /d 1 /f

Invoke-WebRequest -Uri https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1 -OutFile C:\ConfigureRemotingForAnsible.ps1
C:\ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP

Rename-Computer -NewName {{ vm_name }} -Force -Restart
</powershell>

```

After making these two changes, I was able to fix the issue I had :)

**Comment by cigamit** [comment]
I just pushed a commit to develop to fix the newlines for 1).   I pushed a fix earlier today for 2) that removes the 3 new policies that they added to the new AMI that broke things.

**Comment by rmahroua** [comment]
Thanks @cigamit I'll take a look at the fix
