### ISSUE TITLE
WINDC: requests auth method is credssp, but requests-credssp is not installed

### ISSUE THREAD

**Issue by chadhellyea** [mgmt-sa-tiger-team/skylight#8]
TASK [Gathering Facts] ************************************************************************************************************************************************************
fatal: [windc]: UNREACHABLE! => {"changed": false, "msg": "credssp: requests auth method is credssp, but requests-credssp is not installed", "unreachable": true}

**Comment by cigamit** [comment]
Is this happening in the provisioner or during the lesson?
What Ansible version?

**Comment by cigamit** [comment]
If its during provisioning, you will need to install the required modules on your control node.
If its during lesson, what version of Tower are you installing for the students?  3.2 has an issue where it required an extra package, but you should now be installing 3.4, as we updated all the images.

**Comment by cigamit** [comment]
If its during the provisioner, I also recall an bug with the python package for openssl and credssp.  You had to uninstall openssl, install the latest version, then reinstall credssp (pywinrm[credssp]) and requests-credssp.  But that was a while back.

**Comment by chadhellyea** [comment]
ansible --version
ansible 2.7.8

**Comment by cigamit** [comment]
Ok, and it appears to be during the provisioner.  So try this
pip install -U pyopenssl
pip install pywinrm[credssp]
pip install -U requests-credssp

**Comment by chadhellyea** [comment]
What is your environment setup? We are using shell.azure.com/bash with a python virtual environment, which doesn't let us upgrade these packages since they are considered site packages.

Here is our exact config once logged into azure shell:
python3 -m venv ~/ansible_venv
source ~/ansible_venv/bin/activate
echo 'source ~/ansible_venv/bin/activate' >> ~/.bashrc
pip install ansible[azure]
pip install --upgrade pip

**Comment by cigamit** [comment]
My environment is a standard CentOS VM with ansible installed.  Does it not allow you to install requests-credssp into your virtual environment?

**Comment by chadhellyea** [comment]
updated environment in azure shell like this:
python3 -m venv ~/ansible_venv
source ~/ansible_venv/bin/activate
echo 'source ~/ansible_venv/bin/activate' >> ~/.bashrc
pip install ansible[azure]
pip install --upgrade pip
python3 -m pip install --user --upgrade pyopenssl
python3 -m pip install --user --upgrade pywinrm[credssp]
python3 -m pip install --user --upgrade requests-credssp

**Comment by chadhellyea** [comment]
also for azure shell we have to specify the python interpreter with -e ansible_python_interpreter=~/ansible_venv/bin/python

**Comment by chadhellyea** [comment]
can you add you environment config. I have tried from macos, and azure shell. will try from my fedora box later, but now running into oauth errors.
